apiVersion: apps/v1  
kind: Deployment  
metadata:  
  name: my-go-app  
spec:  
  replicas: 1  
  selector:  
    matchLabels:  
      app: my-go-app  
  template:  
    metadata:  
      labels:  
        app: my-go-app  
    spec:  
      containers:  
      - name: my-go-app  
        image: mygoapp
        imagePullPolicy: IfNotPresent
        ports:  
        - containerPort: 8080 
          # env:  
          # - name: REDIS_HOST  
          #          value: "redis:"


---

apiVersion: v1
kind: Service
metadata:
  name: my-go-app
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080 
  selector:
    app: my-go-app

