apiVersion: apps/v1  
kind: Deployment  
metadata:  
  name: my-go-app  
spec:  
  replicas: 1  
  selector:  
    matchLabels:  
      app: my-go-app  
  template:  
    metadata:  
      labels:  
        app: my-go-app  
    spec:  
      containers:  
      - name: my-go-app  
        image: mygoapp
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"         
          limits:
            memory: "512Mi"     
            cpu: "500m"    
        ports:
        - containerPort: 8080 
        env:  
          - name: REDIS_HOST  
            valueFrom:  
              configMapKeyRef:  
                name: example-configmap  
                key: REDIS_HOST  
