apiVersion: v1  
kind: Service  
metadata:  
  name: my-go-app  
spec:  
  type: ClusterIP  
  ports:  
  - port: 8080  # Replace with your Go app's port  
    targetPort: 8080  # Replace with your Go app's container port  
  selector:  
    app: my-go-app
